### ISSUE TITLE
wiring diagram inquiry

### ISSUE THREAD

**Issue by JernejL** [softwarecrash/OmegaFaker#1]
Could you please provide some wiring diagram? 
 
My understanding is to connect digital pin #2 to the "OHM" connector on tool, negative to negative terminal and power it via DC-DC converter to step down from a 40v power source to 5v to power something like a "Pro Micro ATmega32U4 5V 16MHz" Such as this: https://www.aliexpress.com/item/1005003018040519.html 
 
Please confirm if this is correct, or how should this be wired. I have a 40v leaf blower and would like to power it from a 40v power source such as a dewalt 40v battery.

**Comment by softwarecrash** [comment]
> Could you please provide some wiring diagram?
> 
> My understanding is to connect digital pin #2 to the "OHM" connector on tool, negative to negative terminal and power it via DC-DC converter to step down from a 40v power source to 5v to power something like a "Pro Micro ATmega32U4 5V 16MHz" Such as this: https://www.aliexpress.com/item/1005003018040519.html
> 
> Please confirm if this is correct, or how should this be wired. I have a 40v leaf blower and would like to power it from a 40v power source such as a dewalt 40v battery.

Yes correct,
ground from the atmega to the ground of leaf blower
Digital pin from atmega to the OHM 
and from your dewalt 40v to the 40v positiv of the leaf blower
and the dc-dc converter positiv -> dewalt positive, negative to the ground connection.

**Comment by JernejL** [comment]
Ok, i've done so, wired pin 2 to OHM symbol port, and provided a 40v blower with 40 volts. 
However the blower does not start and just blinks the low/high light. Do i need to wire the 4rd pin to something aswell or am i missing something?

**Comment by softwarecrash** [comment]
> Ok, i've done so, wired pin 2 to OHM symbol port, and provided a 40v blower with 40 volts. However the blower does not start and just blinks the low/high light. Do i need to wire the 4rd pin to something aswell or am i missing something?

sounds like the blower have another problem, without omega port the blower start and stops after a second.
have you plugged in or bridged the switches for the air pipe?

**Comment by JernejL** [comment]
I got the blower with missing air pipe and battery, so i'm trying to construct an battery adapter. 
 
It does not start even for a second. So there should be a sensor / switch that detects if the air pipe is missing? 
I could not find this mentioned in the manual that i found online. 
 
Basically the right green (low/high) light just blinks constantly, so if this is sort of protection, where is the air pipe switch hidden?

**Comment by softwarecrash** [comment]
What Type of blower you have?

**Comment by JernejL** [comment]
It is greenworks 24227 brushless blower.

**Comment by softwarecrash** [comment]
Thanks, This blower have a hole over the Air Outlet, in This hole are two switches (Cross locked) you must Push a pice with the Dimension of the hole in it then you Hear two clicks

**Comment by JernejL** [comment]
Can you post a picture? I must be missing something, i do notice a silver bit on one side of blower hole, but it seems to make no difference if i push it in.

**Comment by softwarecrash** [comment]
![20220516_114606](https://user-images.githubusercontent.com/44615614/168566107-f5f5576c-6b14-419f-a6cc-f2e1db39f90f.jpg)
![20220516_114555](https://user-images.githubusercontent.com/44615614/168566125-b3a5b6e5-a367-40a6-ad95-daa4cc56e0d7.jpg)
![20220516_114547](https://user-images.githubusercontent.com/44615614/168566133-727d2285-a522-4004-9e4b-e8ff55a21674.jpg)

**Comment by JernejL** [comment]
I did absolutely not consider that there would be so well hidden switch, it starts now (for 2 seconds) so the tool is good, thank you for the help, it is shameful that the offical manual doesn't mention this feature or error state at all. 
 
I will report when i get arduino working on DC-DC converter, i have one of these: https://www.aliexpress.com/item/33004374185.html in theory LM2596s should work with input voltage 40 volts too?  arduino has minimum power draw anyways.

**Comment by softwarecrash** [comment]
Glad to her that the Machine Work,
The lm2596 is Not the best Option so i think, the max Input is 45v, the battery have 42v with Peak it can kill the lm2596 eventualy.

For Testing you can put a Power Bank or someelse on the arduino, then only Connect arduino Ground to the Machine and the Ohm Pin.

The safety Switch Thing is in the German Manual documentet under Machine fails at the end of the document, it tells only that the Air Pipe oder suction Pipe is Not correctly connected. For normal User This switches Are good, so Take a Look at the impeller.... It have Sharpe knifes to crush the leaf... When anyone Grab into This when running.... Blood everywhere ;)

**Comment by JernejL** [comment]
That's a good idea, i will power it from battery and let you know how it goes.

**Comment by JernejL** [comment]
It works, i used Greenworks40V instead of Greenworks40VRAW because i thought it didn't work first time as my power bank was shutting down as it didn't detect arduino as any discernible load, i assume that both work properly.

**Comment by softwarecrash** [comment]
Nice, happy blowing :)

**Comment by JernejL** [comment]
Indeed happy blowing, and i hope to also design battery adapter for 3d printing.

**Comment by softwarecrash** [comment]
Sounds good, when you have a Adapter to Connect wire to the greenworks Slot please Share it.

**Comment by JernejL** [comment]
Will do, in the end i chose 2x parkside battery as dewalt flexvolt is 60 volts, which is too much.

**Comment by softwarecrash** [comment]
Yes, the greenworks Controllers are Voltage tollerant but 60v for a 40v device is to much.

**Comment by JernejL** [comment]
The adapter will not fit all greenworks devices ass width is not thin enough for those with inside battery covers, but will fit the blower and probably some more devices.

**Comment by softwarecrash** [comment]
Wich Adapter?

**Comment by JernejL** [comment]
![image](https://user-images.githubusercontent.com/1741375/169230379-2bc39d33-38f8-4b0c-838b-da3755798770.png)
 
This is a prototype design, i have only printed and tested pieces of it and not the complete yet, what i was saying is that it would not fit lawnmover due to its width.

**Comment by softwarecrash** [comment]
very nice design, but i htink you can optimize it to fit a 40v slot when the parkside batterys come closer

**Comment by JernejL** [comment]
Maybe if i could mount one from front and another battery from rear, but otherwise even 2x 2ah batteries side by side would be problematic, and 4ah would not fit at all. 
 
![image](https://user-images.githubusercontent.com/1741375/169232168-a3165638-7034-4c3b-9b48-37afef93bc11.png)

Edit: actually parkside batteries are not too wide for front / back design, they are 84mm wide and greenworks seems to be 85.00 mm wide. 
 
Edit 2: that would make adapter too long tho (126.17 * 2) and would not close the lid on lawnmover.

**Comment by softwarecrash** [comment]
ah okay

**Comment by JernejL** [comment]
I'll publish my design once i test it, the shape is good and fits so i hope others can take and improve it further, adapter for 40v dewalt or hilti battery is also possible to make.

**Comment by JernejL** [comment]
Would you say that lower input voltage lm2596 dc-dc converter using just 1 of 2 battery ( off the battery where the negative terminal comes from ).. so from 20v only would be safe option or could that also kill arduino in any way?

**Comment by softwarecrash** [comment]
> Would you say that lower input voltage lm2596 dc-dc converter using just 1 of 2 battery ( off the battery where the negative terminal comes from ).. so from 20v only would be safe option or could that also kill arduino in any way?

the lm2596 have nominal input up to 40V (peak 45V) when you connect it to only one of he 20V batterys it will work

**Comment by JernejL** [comment]
Sorry i haven't yet fulfilled my promise of posting the stl models, but i'm still waiting for high-voltage aliexpress dc-dc converter.

**Comment by JernejL** [comment]
Finally all parts arrived and i have succesfully assembled it, it works great. 
 
Here are the models designed to be 3d printer to fit onto greenworks tools: 
https://www.thingiverse.com/thing:5418541 
 
I have credited you and linked to this project for arduino software. 
 
Aa arduino keeps getting expensive, could this run on ESP32 with a voltage shifter to get 5 volt data logic?

**Comment by softwarecrash** [comment]
> Finally all parts arrived and i have succesfully assembled it, it works great.
> 
> Here are the models designed to be 3d printer to fit onto greenworks tools: https://www.thingiverse.com/thing:5418541
> 
> I have credited you and linked to this project for arduino software.
> 
> Aa arduino keeps getting expensive, could this run on ESP32 with a voltage shifter to get 5 volt data logic?

ESP32 is expensive too ;)
not tested but i think it will work with a ESP82XX
so it will work with a Attiny, there are cheap

**Comment by JernejL** [comment]
Attiny looks great, it would also fit better in the casing. 
 
I've uploaded some pictures of final build aswell, so you can see how it all fits together.

**Comment by softwarecrash** [comment]
> Attiny looks great, it would also fit better in the casing.
> 
> I've uploaded some pictures of final build aswell, so you can see how it all fits together.

your thingi link is not valid

**Comment by JernejL** [comment]
I forgot to finally click publish on thingiverse, my bad. 
 
Link should load now: 
https://www.thingiverse.com/thing:5418541

**Comment by softwarecrash** [comment]
> I forgot to finally click publish on thingiverse, my bad.
> 
> Link should load now: https://www.thingiverse.com/thing:5418541

verrry verry nice work man! looks god

**Comment by JernejL** [comment]
Thanks, i hope you can make use of the models too.

**Comment by softwarecrash** [comment]
> Thanks, i hope you can make use of the models too.

i have only worX and greenworks batterys, so i made this faker only to test a leafblower on a external power supply.

**Comment by JernejL** [comment]
If you have european worx, i can give you STL design for battery receiver, and you can combine that to use on greenworks.

**Comment by softwarecrash** [comment]
thanks but not at the moment, but you can put the link or files here.
i only have a blower and a lawn mower from greenworks, the mower is allready modeded with paralel battery support, so i can run longer
